function shuffle(array: string[]) {
  for (let i = array.length - 1; i > 0; i--) {
    // Generate a random index lower than the current element
    const j = Math.floor(Math.random() * (i + 1));

    // Swap elements at indices i and j
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}

export const WORD_LISTS: Map<string, string[]> = new Map([
  [
    'images',
    shuffle([
      'pan',
      'bag',
      'cat',
      'man',
      'bat',
      'hat',
      'van',
      'fan',
      'rat',
      'mat',
      'jam',
      'map',
      'ham',
      'lad',
      'hen',
      'can',
      'mug',
      'tub',
      'cup',
      'bun',
      'nun',
      'hug',
      'sun',
      'rag',
      'nut',
      'mud',
      'hut',
      'jug',
      'wig',
      'pin',
      'pig',
      'bug',
      'fin',
      'bed',
      'keg',
      'pen',
      'leg',
      'web',

      // 'net',
      // 'peg',
      // 'jet',
      // 'kid',
    ]),
  ],
  [
    'phonetic',
    shuffle([
      // short a
      'pat',
      'tap',
      'mad',
      'had',
      'bad',
      'pad',
      'sat',
      'ran',
      'tax',
      'has',
      'gap',
      'wag',
      'gap',
      'gag',
      'lap',
      'rap',
      'yap',
      'gas',
      'lag',
      'dad',
      'cab',
      'an',
      'as',
      'at',

      // short e
      'ten',
      'men',
      'beg',
      'fed',
      'led',
      'wet',
      'let',
      'pet',
      'set',
      'bet',
      'get',
      'yes',
      'hem',
      'yet',
      'met',
      'vex',
      'den',

      // short i
      'lid',
      'nib',
      'pip',
      'bib',
      'ink',
      'vim',
      'win',
      'dig',
      'hid',
      'hit',
      'sit',
      'it ',
      'gig',
      'bit',
      'big',
      'hit',
      'bin',
      'din',
      'jig',
      'nip',
      'sip',
      'lit',
      'rid',
      'tip',
      'rim',
      'if ',
      'in ',
      'rip',
      'is ',
      'did',
      'dim',
      'fit',
      'him',
      'his',
      'kin',
      'wit',
      'dip',

      // short u
      'gun',
      'bud',
      'rug',
      'bus',
      'sum',
      'pup',
      'tug',
      'cub',
      'rut',
      'sup',
      'pun',
      'mutt',
      'fun',
      'dug',
      'run',
      'gum',
      'but',
      'up',
      'us',
      'rub',
      'hum',
    ]),
  ],
  ['maps', ['map', 'sap', 'maps', 'spam']],
  ['tips', ['tip', 'pit', 'tips', 'spit']],
]);
