function shuffle(array: string[]) {
  for (let i = array.length - 1; i > 0; i--) {
    // Generate a random index lower than the current element
    const j = Math.floor(Math.random() * (i + 1));

    // Swap elements at indices i and j
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}

type WordListRecord = {
  words: string[];
  imageFormat: 'png' | 'jpg';
};

export const WORD_LISTS: Map<string, WordListRecord> = new Map([
  [
    'images',
    {
      words: shuffle([
        // short a
        'bag',
        'bat',
        'bin',
        'cab',
        'cub',
        'can',
        'cat',
        'fan',
        'ham',
        'hat',
        'jam',
        'lad',
        'man',
        'map',
        'mat',
        'pan',
        'rag',
        'rat',
        'van',

        // short e
        'bed',
        'hen',
        'jet',
        'keg',
        'leg',
        'net',
        'peg',
        'pen',
        'web',

        // short i
        'fin',
        'hit',
        'kid',
        'pig',
        'pin',
        'sit',
        'wig',

        // short u
        'bug',
        'bun',
        'bus',
        'cup',
        'hug',
        'hut',
        'jug',
        'mud',
        'mug',
        'nun',
        'nut',
        'run',
        'sun',
        'tub',
      ]),
      imageFormat: 'png',
    },
  ],
  [
    'reading-bear',
    {
      words: shuffle([
        'Ken',
        'Kim',
        'Nick',
        'ask',
        'back',
        'band',
        'belt',
        'bend',
        'bent',
        'buck',
        'bud',
        'bug',
        'bulb',
        'bump',
        'bun',
        'bus',
        'but',
        'buzz',
        'cab',
        'camp',
        'can',
        'cap',
        'cat',
        'cob',
        'cop',
        'cot',
        'cub',
        'cuff',
        'cup',
        'cut',
        'damp',
        'deck',
        'desk',
        'dock',
        'duck',
        'dull',
        'dump',
        'dust',
        'elf',
        'fast',
        'felt',
        'fist',
        'full',
        'fun',
        'fuss',
        'fuzz',
        'gift',
        'gum',
        'help',
        'huff',
        'hug',
        'hum',
        'hut',
        'jump',
        'keg',
        'kick',
        'kid',
        'kin',
        'kiss',
        'lack',
        'land',
        'last',
        'lick',
        'lift',
        'lock',
        'luck',
        'melt',
        'milk',
        'mist',
        'mud',
        'mug',
        'must',
        'mutt',
        'neck',
        'nest',
        'nun',
        'nut',
        'pack',
        'pick',
        'pond',
        'puff',
        'pump',
        'pup',
        'rack',
        'rest',
        'rock',
        'rub',
        'rug',
        'run',
        'sack',
        'sand',
        'self',
        'send',
        'sick',
        'sock',
        'suck',
        'tack',
        'tent',
        'tick',
        'tub',
        'tuck',
        'tug',
        'vest',
        'west',
      ]),
      imageFormat: 'jpg',
    },
  ],
]);
